varsion: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5-stretch-node-browsers-legacy 
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          BUNDLER_VERSION: 2.0.1
          PGHOST: 127.0.0.1
          PGUSER: circleci-demo-ruby
          RAILS_ENV: test
      - image: circleci/postgres:11-alpine-postgis-ram
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: taskleaf
          POSTGRES_PASSWORD: password
    working_directory: ~/taskleaf
    steps:
      - checkout
      - run:
          name: setup bundler
          command: |
            sudo gem update --system
            sudo gem uninstall bundler
            sudo rm -f /usr/local/bin/bundle
            sudo rm -f /usr/local/bin/bundler
            sudo gem install bundler
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      - run:
          name: exec rspec
          command: bundle exec rspec
