varsion: 2.1

jobs:
  build:
    docker:
      - image: cyberious/rspec_puppet:5.5.14
    working_directory: ~/taskleaf
    branches:
      only:
        - master
        - develop
        - /feature\/.*/
    steps:
      - run: rspec
